repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: end-of-file-fixer
    -   id: forbid-new-submodules
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: trailing-whitespace
    -   id: debug-statements
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args: [--config=setup.cfg]
        exclude: ^(examples/*)|(docs/*)
-   repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
    -   id: black
        exclude: ^(build/*)|(docs/*)|(examples/*)
        args: [-l 120, --target-version=py37]
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    -   id: isort
        language_version: python3
        exclude: ^(build/*)|(docs/*)|(examples/*)
        args: [-w120, -m3, --tc, --project=gpytorch]
-   repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
    -   id: require-ascii
        exclude: ^(examples/.*\.ipynb)|(.github/ISSUE_TEMPLATE/*)
    -   id: script-must-have-extension
    -   id: forbid-binary
        exclude: ^(examples/*)|(test/examples/old_variational_strategy_model.pth)
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.4.0
    hooks:
    -   id: forbid-crlf
    -   id: forbid-tabs
